/* =============================================================
   VALORA DECOR — Product Data
   -------------------------------------------------------------
   To add a new product: copy an existing object, change the
   values, and give it a unique `id`. To use a real photo,
   replace `image: null` with `image: "images/your-file.jpg"`.
   ============================================================= */

window.VALORA_PRODUCTS = [
  {
    id: "light-oak-95",
    name: "Light Oak Acoustic Panel",
    category: "acoustic-panel",
    size: "9.5 ft × 2 ft",
    sizeFilter: "9.5x2",
    price: 69,
    priceDisplay: "$69",
    material: "Real wood veneer with acoustic felt backing",
    color: "Light Oak",
    colorFilter: "oak",
    colorSwatch: "#b08d5b",
    roomType: ["living-room", "bedroom", "office", "restaurant"],
    badge: "Bestseller",
    image: null,                    // ← replace with "images/light-oak.jpg"
    texture: "wood-tex--oak",       // visual placeholder class (used when image is null)
    description: "Warm, honey-toned oak veneer finished with premium acoustic felt. A versatile panel that elevates any residential or commercial interior.",
    acousticBacking: "9mm black acoustic felt — NRC ≈ 0.45",
    installation: "Construction silicone or screws. Pre-cut to length.",
    bestUses: ["Accent walls", "Media rooms", "Hotel suites", "Conference rooms"],
    inStock: true
  },
  {
    id: "walnut-95",
    name: "Dark Walnut Acoustic Panel",
    category: "acoustic-panel",
    size: "9.5 ft × 2 ft",
    sizeFilter: "9.5x2",
    price: 79,
    priceDisplay: "$79",
    material: "Real walnut veneer with acoustic felt backing",
    color: "Dark Walnut",
    colorFilter: "walnut",
    colorSwatch: "#5b3f2e",
    roomType: ["office", "restaurant", "bar", "commercial"],
    badge: "New",
    image: null,
    texture: "wood-tex--walnut",
    description: "Rich, espresso-toned walnut with natural grain variation. Designed to anchor premium residential and hospitality spaces.",
    acousticBacking: "9mm black acoustic felt — NRC ≈ 0.45",
    installation: "Construction silicone or screws. Pre-cut to length.",
    bestUses: ["Boardrooms", "Lounges", "Bars", "Luxury residential"],
    inStock: true
  },
  {
    id: "natural-oak-95",
    name: "Natural Oak Acoustic Panel",
    category: "acoustic-panel",
    size: "9.5 ft × 2 ft",
    sizeFilter: "9.5x2",
    price: 69,
    priceDisplay: "$69",
    material: "Real wood veneer with acoustic felt backing",
    color: "Natural Oak",
    colorFilter: "oak",
    colorSwatch: "#c7a06b",
    roomType: ["living-room", "bedroom", "office", "restaurant"],
    badge: null,
    image: null,
    texture: "wood-tex",
    description: "Clean, naturally-grained oak with a soft finish. The most popular choice for modern minimalist interiors.",
    acousticBacking: "9mm black acoustic felt — NRC ≈ 0.45",
    installation: "Construction silicone or screws. Pre-cut to length.",
    bestUses: ["Accent walls", "Podcast studios", "Home theaters"],
    inStock: true
  },
  {
    id: "smoked-ash-95",
    name: "Smoked Ash Acoustic Panel",
    category: "acoustic-panel",
    size: "9.5 ft × 2 ft",
    sizeFilter: "9.5x2",
    price: 74,
    priceDisplay: "$74",
    material: "Real wood veneer with acoustic felt backing",
    color: "Smoked Ash",
    colorFilter: "ash",
    colorSwatch: "#ddd2bf",
    roomType: ["living-room", "office", "bedroom"],
    badge: null,
    image: null,
    texture: "wood-tex--ash",
    description: "Pale, smoky ash tones that brighten darker rooms. Works beautifully with white and stone finishes.",
    acousticBacking: "9mm black acoustic felt — NRC ≈ 0.45",
    installation: "Construction silicone or screws. Pre-cut to length.",
    bestUses: ["Scandinavian interiors", "Medical offices", "Retail"],
    inStock: true
  },
  {
    id: "black-charcoal-95",
    name: "Charcoal Black Acoustic Panel",
    category: "acoustic-panel",
    size: "9.5 ft × 2 ft",
    sizeFilter: "9.5x2",
    price: 84,
    priceDisplay: "$84",
    material: "Matte black wood finish with acoustic felt backing",
    color: "Charcoal Black",
    colorFilter: "black",
    colorSwatch: "#1a1a1a",
    roomType: ["office", "bar", "restaurant", "commercial"],
    badge: "Premium",
    image: null,
    texture: "wood-tex--black",
    description: "A moody, matte-finished panel that adds drama and depth. A contemporary statement piece.",
    acousticBacking: "9mm black acoustic felt — NRC ≈ 0.45",
    installation: "Construction silicone or screws. Pre-cut to length.",
    bestUses: ["Home theaters", "Speakeasies", "Gaming rooms", "Lounges"],
    inStock: true
  },
  {
    id: "oak-veneer-strip",
    name: "Oak Veneer Trim Panel",
    category: "veneer-strip",
    size: "9.5 ft × 6 in",
    sizeFilter: "9.5x0.5",
    price: 13,
    priceDisplay: "$13",
    material: "Real wood veneer strip",
    color: "Natural Oak",
    colorFilter: "oak",
    colorSwatch: "#b08d5b",
    roomType: ["living-room", "bedroom", "kitchen"],
    badge: "Starter",
    image: null,
    texture: "wood-tex--oak",
    description: "A narrow wood trim strip — perfect for borders, ceiling details, and accent highlights without committing to a full panel.",
    acousticBacking: "Trim only — no acoustic backing",
    installation: "Construction silicone or brad nails.",
    bestUses: ["Ceiling accents", "Wall borders", "Slatted dividers"],
    inStock: true
  },
  {
    id: "walnut-veneer-strip",
    name: "Walnut Veneer Trim Panel",
    category: "veneer-strip",
    size: "9.5 ft × 6 in",
    sizeFilter: "9.5x0.5",
    price: 15,
    priceDisplay: "$15",
    material: "Real wood veneer strip",
    color: "Dark Walnut",
    colorFilter: "walnut",
    colorSwatch: "#5b3f2e",
    roomType: ["living-room", "bedroom", "office"],
    badge: null,
    image: null,
    texture: "wood-tex--walnut",
    description: "Rich walnut trim, ideal for framing fireplaces, doorways, and mixed-material accent walls.",
    acousticBacking: "Trim only — no acoustic backing",
    installation: "Construction silicone or brad nails.",
    bestUses: ["Fireplace surrounds", "Door frames", "Ceiling grids"],
    inStock: true
  },
  {
    id: "square-oak-24",
    name: "Oak Square Acoustic Tile",
    category: "square-panel",
    size: "24 in × 24 in",
    sizeFilter: "2x2",
    price: 24,
    priceDisplay: "$24",
    material: "Wood veneer tile with acoustic felt backing",
    color: "Natural Oak",
    colorFilter: "oak",
    colorSwatch: "#b08d5b",
    roomType: ["office", "restaurant", "commercial"],
    badge: null,
    image: null,
    texture: "wood-tex",
    description: "Modular 24\" tiles designed for feature walls and ceilings. Mix and match tones to create custom patterns.",
    acousticBacking: "9mm acoustic felt backing",
    installation: "Adhesive or mechanical fastening.",
    bestUses: ["Ceiling grids", "Modular walls", "Behind reception desks"],
    inStock: true
  },
  {
    id: "square-walnut-24",
    name: "Walnut Square Acoustic Tile",
    category: "square-panel",
    size: "24 in × 24 in",
    sizeFilter: "2x2",
    price: 27,
    priceDisplay: "$27",
    material: "Wood veneer tile with acoustic felt backing",
    color: "Dark Walnut",
    colorFilter: "walnut",
    colorSwatch: "#5b3f2e",
    roomType: ["office", "restaurant", "commercial"],
    badge: null,
    image: null,
    texture: "wood-tex--walnut",
    description: "Modular walnut tiles for grid patterns and premium interior accents.",
    acousticBacking: "9mm acoustic felt backing",
    installation: "Adhesive or mechanical fastening.",
    bestUses: ["Restaurant feature walls", "Hotel lobbies", "Home offices"],
    inStock: true
  },
  {
    id: "mirror-panel-47",
    name: "Decorative Mirror Panel",
    category: "mirror-panel",
    size: "47 in × 24 in",
    sizeFilter: "4x2",
    price: 88,
    priceDisplay: "$88",
    material: "Tempered mirror with wood-frame backing",
    color: "Silver",
    colorFilter: "mirror",
    colorSwatch: "#c9d4d9",
    roomType: ["bathroom", "bedroom", "living-room", "commercial"],
    badge: "Statement",
    image: null,
    texture: "mirror-tex",
    description: "A framed decorative mirror panel that amplifies light and visually expands any space. Ideal paired with wood panels for contrast.",
    acousticBacking: "None — mirror finish",
    installation: "French cleat or heavy-duty adhesive.",
    bestUses: ["Entryways", "Powder rooms", "Salon walls", "Retail"],
    inStock: true
  },
  {
    id: "led-strip-kit",
    name: "Warm White LED Strip Kit",
    category: "lighting",
    size: "16 ft roll",
    sizeFilter: "accessory",
    price: 45,
    priceDisplay: "$45",
    material: "2700K warm white LED with diffuser",
    color: "Warm White",
    colorFilter: "accent",
    colorSwatch: "#f2d9a4",
    roomType: ["living-room", "bedroom", "bar", "commercial"],
    badge: "Add-On",
    image: null,
    texture: "wood-tex--oak",
    description: "Integrated LED strip kit designed to mount behind Valora acoustic panels for a premium back-lit glow.",
    acousticBacking: "N/A",
    installation: "Peel-and-stick adhesive backing + plug-in transformer.",
    bestUses: ["Backlit accent walls", "Headboard lighting", "Bar shelving"],
    inStock: true
  },
  {
    id: "installation-service",
    name: "Professional Installation",
    category: "service",
    size: "Per project",
    sizeFilter: "accessory",
    price: null,
    priceDisplay: "Quote on request",
    material: "Licensed local installation crew (Atlanta Metro)",
    color: "—",
    colorFilter: "accent",
    colorSwatch: "#0d0d0d",
    roomType: ["living-room", "office", "restaurant", "commercial", "bathroom"],
    badge: "Service",
    image: null,
    texture: "wood-tex--walnut",
    description: "Let our certified installers handle your project end-to-end. Available across Alpharetta, Atlanta, and North Georgia.",
    acousticBacking: "N/A",
    installation: "Full-service — measurement, cutting, mounting, and cleanup.",
    bestUses: ["Large accent walls", "Commercial rollouts", "Multi-room projects"],
    inStock: true
  }
];

/* =============================================================
   Filter dictionaries (used by Products page).
   Add / rename entries here to change filter dropdown options.
   ============================================================= */
window.VALORA_FILTERS = {
  color: [
    { value: "all",    label: "All colors" },
    { value: "oak",    label: "Oak" },
    { value: "walnut", label: "Walnut" },
    { value: "ash",    label: "Ash" },
    { value: "black",  label: "Black" },
    { value: "mirror", label: "Mirror" },
    { value: "accent", label: "Accent" }
  ],
  size: [
    { value: "all",    label: "All sizes" },
    { value: "9.5x2",  label: "9.5 ft × 2 ft" },
    { value: "9.5x0.5",label: "9.5 ft × 6 in" },
    { value: "2x2",    label: "24 in × 24 in" },
    { value: "4x2",    label: "47 in × 24 in" },
    { value: "accessory", label: "Accessory / Service" }
  ],
  material: [
    { value: "all",              label: "All materials" },
    { value: "acoustic-panel",   label: "Acoustic Panel" },
    { value: "veneer-strip",     label: "Veneer Trim" },
    { value: "square-panel",     label: "Square Tile" },
    { value: "mirror-panel",     label: "Mirror Panel" },
    { value: "lighting",         label: "LED Lighting" },
    { value: "service",          label: "Service" }
  ],
  room: [
    { value: "all",         label: "All rooms" },
    { value: "living-room", label: "Living Room" },
    { value: "bedroom",     label: "Bedroom" },
    { value: "office",      label: "Office" },
    { value: "restaurant",  label: "Restaurant" },
    { value: "bar",         label: "Bar / Lounge" },
    { value: "bathroom",    label: "Bathroom" },
    { value: "commercial",  label: "Commercial" },
    { value: "kitchen",     label: "Kitchen" }
  ]
};
